Revert "Replace tabs by spaces"
This reverts commit 773af43fb8b11f90601b30be6836ab629b6856e1.

diff --git a/sfeed/sfeed_opml_export b/sfeed/sfeed_opml_export
--- a/sfeed/sfeed_opml_export
+++ b/sfeed/sfeed_opml_export
@@ -3,32 +3,32 @@
 # load config (evaluate shellscript).
 # loadconfig(configfile)
 loadconfig() {
-  # allow to specify config via argv[1].
-  if [ "$1" != "" ]; then
-    # get absolute path of config file required for including.
-    config="$1"
-    path=$(readlink -f "${config}" 2>/dev/null)
-  else
-    # default config location.
-    config="$HOME/.sfeed/sfeedrc"
-    path="${config}"
-  fi
+	# allow to specify config via argv[1].
+	if [ "$1" != "" ]; then
+		# get absolute path of config file required for including.
+		config="$1"
+		path=$(readlink -f "${config}" 2>/dev/null)
+	else
+		# default config location.
+		config="$HOME/.sfeed/sfeedrc"
+		path="${config}"
+	fi
 
-  # config is loaded here to be able to override $sfeedpath or functions.
-  if [ -r "${path}" ]; then
-    . "${path}"
-  else
-    echo "Configuration file \"${config}\" cannot be read." >&2
-    echo "See sfeedrc.example for an example." >&2
-    exit 1
-  fi
+	# config is loaded here to be able to override $sfeedpath or functions.
+	if [ -r "${path}" ]; then
+		. "${path}"
+	else
+		echo "Configuration file \"${config}\" cannot be read." >&2
+		echo "See sfeedrc.example for an example." >&2
+		exit 1
+	fi
 }
 
 # override feed function to output OPML XML.
 # feed(name, feedurl, [basesiteurl], [encoding])
 feed() {
-  # NOTE: TABs in field values are unsupported, be sane.
-  echo "$1  $2"
+	# NOTE: TABs in field values are unsupported, be sane.
+	echo "$1	$2"
 }
 
 # load config file.
@@ -38,19 +38,19 @@ cat <<!
 <?xml version="1.0" encoding="UTF-8"?>
 <opml version="1.0">
 <head>
-  <title>OPML export from sfeed</title>
+	<title>OPML export from sfeed</title>
 </head>
 <body>
 !
 
 feeds | awk -F '\t' '{
-  gsub("&", "\\&amp;");
-  gsub("\"", "\\&quot;");
-  gsub("'"'"'", "\\&#39;");
-  gsub("<", "\\&lt;");
-  gsub(">", "\\&gt;");
+	gsub("&", "\\&amp;");
+	gsub("\"", "\\&quot;");
+	gsub("'"'"'", "\\&#39;");
+	gsub("<", "\\&lt;");
+	gsub(">", "\\&gt;");
 
-  print "\t<outline type=\"rss\" title=\"" $1 "\" text=\"" $1 "\" xmlUrl=\"" $2 "\"/>";
+	print "\t<outline type=\"rss\" title=\"" $1 "\" text=\"" $1 "\" xmlUrl=\"" $2 "\"/>";
 }'
 
 cat <<!
